name: CI

on:
  push:
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use node js
        uses: actions/setup-node@v1
        with:
          node_version: "12.x"
      - name: Install dependencies
        run: npm ci
      - name: Check code formatting
        run: npm run format:check
      - name: Run tests
        run: npm test -- --coverage
        env:
          CI: true